"""empty message

Revision ID: 03ebb3880189
Revises: b2909355dd4f
Create Date: 2021-04-24 11:08:59.287906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ebb3880189'
down_revision = 'b2909355dd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportcenter', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sportcenter', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sportcenter', type_='foreignkey')
    op.drop_column('sportcenter', 'user_id')
    # ### end Alembic commands ###
