"""empty message

Revision ID: 14d4cbb0fcf9
Revises: f288aa4c92bf
Create Date: 2021-04-09 18:23:22.078710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d4cbb0fcf9'
down_revision = 'f288aa4c92bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
