"""empty message

Revision ID: 2fe4e7a0a272
Revises: a91773104103
Create Date: 2021-05-22 19:20:54.412987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe4e7a0a272'
down_revision = 'a91773104103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'datetime')
    # ### end Alembic commands ###
