"""empty message

Revision ID: 3145068d34be
Revises: 7ff689643b35
Create Date: 2021-04-07 15:04:08.360168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3145068d34be'
down_revision = '7ff689643b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paymethod', sa.Integer(), nullable=False),
    sa.Column('id_hours', sa.Integer(), nullable=False),
    sa.Column('id_courts', sa.Integer(), nullable=False),
    sa.Column('admin_user', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('center_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('webpage', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('admin_user'),
    sa.UniqueConstraint('center_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('webpage')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_center')
    # ### end Alembic commands ###
