"""empty message

Revision ID: 3420af6bde1d
Revises: 7faa17f3e741
Create Date: 2021-05-17 14:37:41.324941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3420af6bde1d'
down_revision = '7faa17f3e741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'birth')
    # ### end Alembic commands ###
