"""empty message

Revision ID: 372afed46188
Revises: fc4eaf38a996
Create Date: 2021-05-06 17:27:21.437785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372afed46188'
down_revision = 'fc4eaf38a996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prebooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date_time_start', sa.DateTime(), nullable=False),
    sa.Column('booking_date_time_end', sa.DateTime(), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('sportcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sportcenter_id'], ['sportcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prebooking')
    # ### end Alembic commands ###
