"""empty message

Revision ID: 378d1ef1caad
Revises: 55342e76b959
Create Date: 2021-05-22 10:59:50.315165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378d1ef1caad'
down_revision = '55342e76b959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend', 'userfriend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friend', 'username',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend', 'username',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('friend', 'userfriend_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
