"""empty message

Revision ID: 3d5a350ae814
Revises: ea4efcff87af
Create Date: 2021-04-11 11:16:02.009142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5a350ae814'
down_revision = 'ea4efcff87af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_name', sa.String(length=120), nullable=False),
    sa.Column('light', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court')
    # ### end Alembic commands ###
