"""empty message

Revision ID: 435276f21024
Revises: 5f1fb1921ee6
Create Date: 2021-05-09 12:32:30.365020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435276f21024'
down_revision = '5f1fb1921ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prebooking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prebooking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prebooking', type_='foreignkey')
    op.drop_column('prebooking', 'user_id')
    # ### end Alembic commands ###
