"""empty message

Revision ID: 55342e76b959
Revises: 105f38ac2193
Create Date: 2021-05-22 10:57:25.073180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55342e76b959'
down_revision = '105f38ac2193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('userfriend_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'friend', ['userfriend_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend', type_='unique')
    op.drop_column('friend', 'userfriend_id')
    # ### end Alembic commands ###
