"""empty message

Revision ID: 56eb9715c88e
Revises: 1a075b5757a8
Create Date: 2021-05-01 11:07:02.205790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eb9715c88e'
down_revision = '1a075b5757a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'is_active')
    # ### end Alembic commands ###
