"""empty message

Revision ID: 5e98fd50db80
Revises: fb97b3567eae
Create Date: 2021-05-05 17:15:18.310702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e98fd50db80'
down_revision = 'fb97b3567eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date_time_start', sa.DateTime(), nullable=False),
    sa.Column('booking_date_time_end', sa.DateTime(), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sportcenter', sa.Column('closing_time', sa.Integer(), nullable=False))
    op.add_column('sportcenter', sa.Column('opening_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sportcenter', 'opening_time')
    op.drop_column('sportcenter', 'closing_time')
    op.drop_table('booking')
    # ### end Alembic commands ###
