"""empty message

Revision ID: 5f1fb1921ee6
Revises: caad077eed81
Create Date: 2021-05-07 17:05:44.301545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1fb1921ee6'
down_revision = 'caad077eed81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.add_column('prebooking', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prebooking', 'datetime')
    op.drop_column('booking', 'datetime')
    # ### end Alembic commands ###
