"""empty message

Revision ID: 7149fe9e08bb
Revises: 03ebb3880189
Create Date: 2021-04-24 11:22:00.875646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7149fe9e08bb'
down_revision = '03ebb3880189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sportcenter_admin_user_key', 'sportcenter', type_='unique')
    op.drop_constraint('sportcenter_email_key', 'sportcenter', type_='unique')
    op.drop_column('sportcenter', 'image')
    op.drop_column('sportcenter', 'email')
    op.drop_column('sportcenter', 'admin_user')
    op.drop_column('sportcenter', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportcenter', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('sportcenter', sa.Column('admin_user', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('sportcenter', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('sportcenter', sa.Column('image', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('sportcenter_email_key', 'sportcenter', ['email'])
    op.create_unique_constraint('sportcenter_admin_user_key', 'sportcenter', ['admin_user'])
    # ### end Alembic commands ###
