"""empty message

Revision ID: 7247031ac78f
Revises: 1fb65649930c
Create Date: 2021-04-21 14:35:55.190992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7247031ac78f'
down_revision = '1fb65649930c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_data', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_data')
    # ### end Alembic commands ###
