"""empty message

Revision ID: 72df9def3d8d
Revises: 7462698f5449
Create Date: 2021-05-31 21:51:41.173359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72df9def3d8d'
down_revision = '7462698f5449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('username', sa.String(length=120), nullable=True))
    op.add_column('comment', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'datetime')
    op.drop_column('comment', 'username')
    # ### end Alembic commands ###
