"""empty message

Revision ID: 7462698f5449
Revises: 75d56586be6b
Create Date: 2021-05-30 15:43:39.412278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7462698f5449'
down_revision = '75d56586be6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friend_userfriend_id_key', 'friend', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('friend_userfriend_id_key', 'friend', ['userfriend_id'])
    # ### end Alembic commands ###
