"""empty message

Revision ID: 74f5eca0de12
Revises: 372afed46188
Create Date: 2021-05-06 17:44:00.004260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f5eca0de12'
down_revision = '372afed46188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportcenter', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sportcenter', 'capacity')
    # ### end Alembic commands ###
