"""empty message

Revision ID: 75d56586be6b
Revises: e2c3ff5ae03e
Create Date: 2021-05-30 15:42:20.276055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d56586be6b'
down_revision = 'e2c3ff5ae03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friend_username_key', 'friend', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('friend_username_key', 'friend', ['username'])
    # ### end Alembic commands ###
