"""empty message

Revision ID: 7faa17f3e741
Revises: aff36f29a45e
Create Date: 2021-05-16 20:18:03.059501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faa17f3e741'
down_revision = 'aff36f29a45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prebooking', sa.Column('court_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prebooking', 'court_name')
    # ### end Alembic commands ###
