"""empty message

Revision ID: 81246bfabf10
Revises: 21cdae9ee9a8
Create Date: 2021-04-09 18:22:25.053671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81246bfabf10'
down_revision = '21cdae9ee9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=-1)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
