"""empty message

Revision ID: 84b6ca25a318
Revises: 9bc54fb5251a
Create Date: 2021-04-09 16:48:01.271418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b6ca25a318'
down_revision = '9bc54fb5251a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_center', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('new_center', sa.Column('cp', sa.Integer(), nullable=False))
    op.add_column('new_center', sa.Column('state', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_center', 'state')
    op.drop_column('new_center', 'cp')
    op.drop_column('new_center', 'city')
    # ### end Alembic commands ###
