"""empty message

Revision ID: 850d84c3a203
Revises: b2072887bfb4
Create Date: 2021-04-28 18:48:36.391916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850d84c3a203'
down_revision = 'b2072887bfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
