"""empty message

Revision ID: 90fca169c692
Revises: 0c24743bdc03
Create Date: 2021-05-22 20:03:59.973854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fca169c692'
down_revision = '0c24743bdc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_url_image', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'user_url_image')
    # ### end Alembic commands ###
