"""empty message

Revision ID: 948aa233c50f
Revises: 850d84c3a203
Create Date: 2021-04-29 19:33:57.164157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948aa233c50f'
down_revision = '850d84c3a203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
