"""empty message

Revision ID: a91773104103
Revises: 378d1ef1caad
Create Date: 2021-05-22 11:00:14.311206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91773104103'
down_revision = '378d1ef1caad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend', 'userfriend_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friend', 'username',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend', 'username',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('friend', 'userfriend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
