"""empty message

Revision ID: aadc222754f2
Revises: 3145068d34be
Create Date: 2021-04-07 19:18:26.310618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadc222754f2'
down_revision = '3145068d34be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_center', 'id_paymethod')
    op.drop_column('new_center', 'id_courts')
    op.drop_column('new_center', 'id_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_center', sa.Column('id_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('new_center', sa.Column('id_courts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('new_center', sa.Column('id_paymethod', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
