"""empty message

Revision ID: aff36f29a45e
Revises: c980463a54ba
Create Date: 2021-05-16 10:06:07.975794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aff36f29a45e'
down_revision = 'c980463a54ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'players')
    op.drop_column('booking', 'time_end')
    op.drop_column('booking', 'time_start')
    op.drop_column('booking', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('players', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
