"""empty message

Revision ID: b2909355dd4f
Revises: 7247031ac78f
Create Date: 2021-04-21 17:30:17.220853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2909355dd4f'
down_revision = '7247031ac78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url_image', sa.String(length=120), nullable=False))
    op.drop_column('images', 'image_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_data', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('images', 'url_image')
    # ### end Alembic commands ###
