"""empty message

Revision ID: c980463a54ba
Revises: d41910eaa543
Create Date: 2021-05-16 09:34:33.152285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c980463a54ba'
down_revision = 'd41910eaa543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prebooking', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prebooking', 'booking', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prebooking', type_='foreignkey')
    op.drop_column('prebooking', 'booking_id')
    # ### end Alembic commands ###
