"""empty message

Revision ID: caad077eed81
Revises: 74f5eca0de12
Create Date: 2021-05-07 13:59:30.102026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'caad077eed81'
down_revision = '74f5eca0de12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('booking', sa.Column('time_end', sa.Time(), nullable=False))
    op.add_column('booking', sa.Column('time_start', sa.Time(), nullable=False))
    op.drop_column('booking', 'booking_date_time_start')
    op.drop_column('booking', 'booking_date_time_end')
    op.add_column('prebooking', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('prebooking', sa.Column('time_end', sa.Time(), nullable=False))
    op.add_column('prebooking', sa.Column('time_start', sa.Time(), nullable=False))
    op.drop_column('prebooking', 'booking_date_time_start')
    op.drop_column('prebooking', 'booking_date_time_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prebooking', sa.Column('booking_date_time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('prebooking', sa.Column('booking_date_time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('prebooking', 'time_start')
    op.drop_column('prebooking', 'time_end')
    op.drop_column('prebooking', 'date')
    op.add_column('booking', sa.Column('booking_date_time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('booking_date_time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('booking', 'time_start')
    op.drop_column('booking', 'time_end')
    op.drop_column('booking', 'date')
    # ### end Alembic commands ###
