"""empty message

Revision ID: cf77159baf44
Revises: 
Create Date: 2021-04-25 10:15:48.681955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf77159baf44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sportcenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=120), nullable=False),
    sa.Column('nif', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('webpage', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('cp', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_name'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('court',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_name', sa.String(length=120), nullable=False),
    sa.Column('light', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('sportcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sportcenter_id'], ['sportcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_image', sa.String(length=120), nullable=False),
    sa.Column('sportcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sportcenter_id'], ['sportcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('court')
    op.drop_table('sportcenter')
    op.drop_table('user')
    # ### end Alembic commands ###
