"""empty message

Revision ID: d41910eaa543
Revises: f17cadcc8fb0
Create Date: 2021-05-15 09:54:52.002015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41910eaa543'
down_revision = 'f17cadcc8fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prebooking', sa.Column('isConfirm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prebooking', 'isConfirm')
    # ### end Alembic commands ###
