"""empty message

Revision ID: d7db2af005c3
Revises: 84b6ca25a318
Create Date: 2021-04-09 18:02:42.139163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7db2af005c3'
down_revision = '84b6ca25a318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=-1)
    op.drop_column('new_center', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_center', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('new_center', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
