"""empty message

Revision ID: e84fa54804f7
Revises: fe7e8e7f0d2d
Create Date: 2021-04-12 13:52:55.986985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84fa54804f7'
down_revision = 'fe7e8e7f0d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court', sa.Column('players', sa.Integer(), nullable=False))
    op.alter_column('court', 'court_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('court', 'court_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('court', 'players')
    # ### end Alembic commands ###
