"""empty message

Revision ID: ea4efcff87af
Revises: 14d4cbb0fcf9
Create Date: 2021-04-11 10:12:24.241899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4efcff87af'
down_revision = '14d4cbb0fcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=120), nullable=False),
    sa.Column('nif', sa.String(length=120), nullable=False),
    sa.Column('admin_user', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('webpage', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('cp', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user'),
    sa.UniqueConstraint('center_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('phone')
    )
    op.drop_table('new_center')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_center',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_user', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('center_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('webpage', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('nif', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('cp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='new_center_pkey')
    )
    op.drop_table('sport_center')
    # ### end Alembic commands ###
