"""empty message

Revision ID: f288aa4c92bf
Revises: 81246bfabf10
Create Date: 2021-04-09 18:23:01.855197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f288aa4c92bf'
down_revision = '81246bfabf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
