"""empty message

Revision ID: fb97b3567eae
Revises: 56eb9715c88e
Create Date: 2021-05-01 11:16:15.152676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb97b3567eae'
down_revision = '56eb9715c88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_column('like', 'user_id')
    # ### end Alembic commands ###
