"""empty message

Revision ID: fe7e8e7f0d2d
Revises: c9a847c90f32
Create Date: 2021-04-11 12:37:59.316947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7e8e7f0d2d'
down_revision = 'c9a847c90f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sportcenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=120), nullable=False),
    sa.Column('nif', sa.String(length=120), nullable=False),
    sa.Column('admin_user', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('webpage', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('cp', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user'),
    sa.UniqueConstraint('center_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('phone')
    )
    op.drop_table('sport_center')
    op.add_column('court', sa.Column('sportcenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'court', 'sportcenter', ['sportcenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'court', type_='foreignkey')
    op.drop_column('court', 'sportcenter_id')
    op.create_table('sport_center',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('center_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nif', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('admin_user', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('webpage', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('cp', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sport_center_pkey'),
    sa.UniqueConstraint('admin_user', name='sport_center_admin_user_key'),
    sa.UniqueConstraint('center_name', name='sport_center_center_name_key'),
    sa.UniqueConstraint('email', name='sport_center_email_key'),
    sa.UniqueConstraint('nif', name='sport_center_nif_key'),
    sa.UniqueConstraint('phone', name='sport_center_phone_key')
    )
    op.drop_table('sportcenter')
    # ### end Alembic commands ###
