"""empty message

Revision ID: feee90c7670f
Revises: d7db2af005c3
Create Date: 2021-04-09 18:13:06.751637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feee90c7670f'
down_revision = 'd7db2af005c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_center', sa.Column('state', sa.String(length=120), nullable=True))
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=-1)
    op.alter_column('new_center', 'image',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_center', 'image',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('new_center', 'cp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('new_center', 'state')
    # ### end Alembic commands ###
